INSERT OR IGNORE INTO techniques (id, name, category, description, created_at) VALUES
('tech-bijection', 'Bijection', 'Combinatorics', 'Recast two sets of objects in a one-to-one correspondence.', CURRENT_TIMESTAMP),
('tech-double-counting', 'Double counting', 'Combinatorics', 'Count the same collection in two different ways.', CURRENT_TIMESTAMP),
('tech-pigeonhole', 'Pigeonhole principle', 'Combinatorics', 'Force repetition or concentration by comparing objects and boxes.', CURRENT_TIMESTAMP),
('tech-inclusion-exclusion', 'Inclusion-exclusion', 'Combinatorics', 'Correct overlapping counts by alternating intersections.', CURRENT_TIMESTAMP),
('tech-invariant', 'Invariant', 'Combinatorics', 'Track a quantity that cannot change under allowed operations.', CURRENT_TIMESTAMP),
('tech-monovariant', 'Monovariant', 'Combinatorics', 'Track a quantity that moves strictly in one direction.', CURRENT_TIMESTAMP),
('tech-extremal', 'Extremal principle', 'General', 'Choose a largest, smallest, earliest, or latest object and exploit it.', CURRENT_TIMESTAMP),
('tech-graph', 'Graph modeling', 'Combinatorics', 'Represent relationships as vertices and edges.', CURRENT_TIMESTAMP),
('tech-generating-functions', 'Generating functions', 'Combinatorics', 'Encode a sequence or counting problem as coefficients of a power series.', CURRENT_TIMESTAMP),
('tech-recurrence', 'Recurrence relation', 'General', 'Relate the current case to smaller or previous cases.', CURRENT_TIMESTAMP),
('tech-probabilistic', 'Probabilistic method', 'Combinatorics', 'Prove existence by showing positive probability.', CURRENT_TIMESTAMP),
('tech-coloring', 'Coloring argument', 'Combinatorics', 'Assign colors to reveal parity, adjacency, or impossibility.', CURRENT_TIMESTAMP),
('tech-stars-bars', 'Stars and bars', 'Combinatorics', 'Count nonnegative integer solutions or distributions.', CURRENT_TIMESTAMP),
('tech-modular', 'Modular arithmetic', 'Number Theory', 'Reduce arithmetic to congruence classes.', CURRENT_TIMESTAMP),
('tech-parity', 'Parity', 'Number Theory', 'Separate even and odd behavior.', CURRENT_TIMESTAMP),
('tech-valuation', 'Prime valuations', 'Number Theory', 'Compare exponents of primes in factorizations.', CURRENT_TIMESTAMP),
('tech-gcd', 'GCD and divisibility', 'Number Theory', 'Exploit common divisors and coprimality.', CURRENT_TIMESTAMP),
('tech-diophantine-factor', 'Diophantine factorization', 'Number Theory', 'Rearrange an integer equation into factor pairs.', CURRENT_TIMESTAMP),
('tech-descent', 'Infinite descent', 'Number Theory', 'Turn a minimal counterexample into a smaller one.', CURRENT_TIMESTAMP),
('tech-crt', 'Chinese remainder theorem', 'Number Theory', 'Combine compatible congruence conditions.', CURRENT_TIMESTAMP),
('tech-order', 'Multiplicative order', 'Number Theory', 'Use periodicity of powers modulo an integer.', CURRENT_TIMESTAMP),
('tech-quadratic-residues', 'Quadratic residues', 'Number Theory', 'Analyze which congruence classes can be squares.', CURRENT_TIMESTAMP),
('tech-vieta-jumping', 'Vieta jumping', 'Number Theory', 'Generate a smaller integer solution using roots of a quadratic.', CURRENT_TIMESTAMP),
('tech-factor-polynomial', 'Polynomial factorization', 'Algebra', 'Use roots, identities, or structure to factor a polynomial.', CURRENT_TIMESTAMP),
('tech-symmetric-polynomials', 'Symmetric polynomials', 'Algebra', 'Rewrite expressions using elementary symmetric quantities.', CURRENT_TIMESTAMP),
('tech-substitution', 'Strategic substitution', 'Algebra', 'Introduce a new variable or expression that exposes structure.', CURRENT_TIMESTAMP),
('tech-amgm', 'AM-GM inequality', 'Algebra', 'Compare arithmetic and geometric means.', CURRENT_TIMESTAMP),
('tech-cauchy', 'Cauchy-Schwarz inequality', 'Algebra', 'Control sums and products through quadratic structure.', CURRENT_TIMESTAMP),
('tech-convexity', 'Convexity', 'Analysis', 'Use tangent lines, Jensen-type reasoning, or curvature.', CURRENT_TIMESTAMP),
('tech-functional', 'Functional equations', 'Algebra', 'Choose inputs that force constraints on an unknown function.', CURRENT_TIMESTAMP),
('tech-complex', 'Complex numbers', 'Algebra', 'Use magnitude, argument, roots, or algebra over the complex plane.', CURRENT_TIMESTAMP),
('tech-linear-algebra', 'Linear algebra', 'Algebra', 'Use vectors, matrices, rank, eigenvalues, or dimension.', CURRENT_TIMESTAMP),
('tech-continuity', 'Continuity and IVT', 'Analysis', 'Use continuity to force an intermediate value or fixed behavior.', CURRENT_TIMESTAMP),
('tech-calculus', 'Calculus and derivatives', 'Analysis', 'Use differentiation, integration, or local variation.', CURRENT_TIMESTAMP),
('tech-telescoping', 'Telescoping', 'Analysis', 'Arrange cancellation across a sum or product.', CURRENT_TIMESTAMP),
('tech-estimation', 'Sharp estimation', 'Analysis', 'Build upper and lower bounds that meet or nearly meet.', CURRENT_TIMESTAMP),
('tech-compactness', 'Compactness', 'Analysis', 'Extract finite control, extrema, or convergent subsequences.', CURRENT_TIMESTAMP),
('tech-coordinate', 'Coordinate geometry', 'Geometry', 'Translate geometry into equations and coordinates.', CURRENT_TIMESTAMP),
('tech-vectors', 'Vectors', 'Geometry', 'Use vector addition, dot products, or affine combinations.', CURRENT_TIMESTAMP),
('tech-transform', 'Geometric transformation', 'Geometry', 'Apply reflection, rotation, dilation, or inversion.', CURRENT_TIMESTAMP),
('tech-area', 'Area method', 'Geometry', 'Relate lengths and ratios through areas.', CURRENT_TIMESTAMP),
('tech-angle', 'Angle chasing', 'Geometry', 'Propagate angle equalities through the configuration.', CURRENT_TIMESTAMP),
('tech-induction', 'Induction', 'General', 'Prove a statement by a base case and a transition.', CURRENT_TIMESTAMP),
('tech-contradiction', 'Contradiction', 'General', 'Assume the opposite and derive an impossibility.', CURRENT_TIMESTAMP),
('tech-casework', 'Structured casework', 'General', 'Partition possibilities into exhaustive, non-overlapping cases.', CURRENT_TIMESTAMP),
('tech-normalize', 'Normalization', 'General', 'Scale or transform the problem to remove an irrelevant parameter.', CURRENT_TIMESTAMP),
('tech-auxiliary', 'Auxiliary construction', 'General', 'Create an object, sequence, graph, or lemma that exposes the solution.', CURRENT_TIMESTAMP),
('tech-reverse', 'Reverse engineering', 'General', 'Work backward from the desired conclusion or equality case.', CURRENT_TIMESTAMP),
('tech-small-cases', 'Small cases and pattern finding', 'General', 'Compute examples to discover the right conjecture or structure.', CURRENT_TIMESTAMP);
