PRAGMA foreign_keys = ON;

INSERT OR IGNORE INTO catalog_problems (id, title, source, statement, year, session, number, area, topics_json, concepts_json, techniques_json, prerequisites_json, difficulty_overall, difficulty_insight, difficulty_technical, difficulty_prerequisite, difficulty_proof, difficulty_confidence, key_observation, solution_architecture, common_false_starts_json, classification_status) VALUES
  ('putnam_1962_a1', '1962 Putnam A1', '1962 William Lowell Putnam Mathematical Competition A1', 'Given five points in a plane, no three of which lie on a straight line, show that some four of these points form the vertices of a convex quadrilateral.', 1962, 'A', 1, 'Geometry', '["Geometry","Combinatorial geometry"]', '["Convex hull","Convex quadrilateral","General position"]', '["Extremal principle","Case analysis","Geometric construction"]', '["Elementary Euclidean geometry","Convexity basics"]', 2.5, 3.0, 1.5, 1.5, 2.5, 0.65, 'Either one point lies inside the quadrilateral formed by four others, or four points appear as vertices of the convex hull.', 'Pass to the convex hull of the five points, split by the number of hull vertices, and select four suitable vertices.', '["Trying to order the points by coordinates","Assuming all five points are already in convex position"]', 'reviewed_seed');

INSERT OR IGNORE INTO catalog_problems (id, title, source, statement, year, session, number, area, topics_json, concepts_json, techniques_json, prerequisites_json, difficulty_overall, difficulty_insight, difficulty_technical, difficulty_prerequisite, difficulty_proof, difficulty_confidence, key_observation, solution_architecture, common_false_starts_json, classification_status) VALUES
  ('putnam_1962_a2', '1962 Putnam A2', '1962 William Lowell Putnam Mathematical Competition A2', 'Find every real-valued function f whose domain is an interval I (finite or infinite) having 0 as a left-hand endpoint, such that for every positive x in I the average of f over [0,x] equals the geometric mean of f(0) and f(x).', 1962, 'A', 2, 'Mixed', '["Real analysis","Functional equations","Differential equations"]', '["Integral averages","Differentiation under an identity","Separable differential equation"]', '["Differentiate a functional identity","Normalize constants","Solve an induced ODE"]', '["Fundamental theorem of calculus","Ordinary differential equations","Continuity"]', 5.0, 5.5, 4.5, 4.0, 4.5, 0.65, 'After naming the integral F(x), the condition relates F(x)/x to f(x), and differentiating converts the problem into an ODE.', 'Rewrite with an accumulated integral, differentiate, solve the resulting differential equation, and verify the domain and positivity conditions.', '["Guessing only constant solutions","Squaring without checking signs or positivity"]', 'reviewed_seed');

INSERT OR IGNORE INTO catalog_problems (id, title, source, statement, year, session, number, area, topics_json, concepts_json, techniques_json, prerequisites_json, difficulty_overall, difficulty_insight, difficulty_technical, difficulty_prerequisite, difficulty_proof, difficulty_confidence, key_observation, solution_architecture, common_false_starts_json, classification_status) VALUES
  ('putnam_1962_a3', '1962 Putnam A3', '1962 William Lowell Putnam Mathematical Competition A3', 'Let ABC be a triangle, with P,Q,R on BC,CA,AB respectively such that AQ/QC = BR/RA = CP/PB = k>0. If UVW is the triangle formed by the three cevians AP,BQ,CR, prove that [UVW]/[ABC] = (k-1)^2/(k^2+k+1).', 1962, 'A', 3, 'Geometry', '["Geometry","Affine geometry"]', '["Cevians","Area ratios","Barycentric coordinates","Routh-type formula"]', '["Affine normalization","Coordinate geometry","Determinant computation"]', '["Triangle area formulas","Solving linear equations","Determinants"]', 5.5, 5.0, 6.0, 3.5, 5.0, 0.6, 'Area ratios are invariant under affine transformations, so the triangle may be placed at convenient coordinates.', 'Normalize ABC to a coordinate triangle, compute the three cevian intersections, then take a determinant ratio.', '["Using angle chasing in a purely affine problem","Computing many lengths instead of areas"]', 'reviewed_seed');

INSERT OR IGNORE INTO catalog_problems (id, title, source, statement, year, session, number, area, topics_json, concepts_json, techniques_json, prerequisites_json, difficulty_overall, difficulty_insight, difficulty_technical, difficulty_prerequisite, difficulty_proof, difficulty_confidence, key_observation, solution_architecture, common_false_starts_json, classification_status) VALUES
  ('putnam_1962_a4', '1962 Putnam A4', '1962 William Lowell Putnam Mathematical Competition A4', 'Assume |f(x)|<=1 and |f''''(x)|<=1 for all x on an interval of length at least 2. Show that |f''(x)|<=2 on the interval.', 1962, 'A', 4, 'Mixed', '["Real analysis","Inequalities"]', '["Derivative bounds","Taylor theorem","Mean value theorem"]', '["Choose a favorable nearby point","Taylor expansion with remainder","Contradiction by growth"]', '["Differentiation","Taylor theorem or mean value theorem"]', 5.5, 6.0, 3.5, 3.0, 4.5, 0.7, 'If the derivative were too large, bounded curvature would keep it large long enough to force f to change by more than 2.', 'Select a point one unit away on the available side, apply Taylor''s theorem, and combine the bounds on f and f''''.', '["Applying the mean value theorem only once","Trying to maximize f'' without using the interval-length condition"]', 'reviewed_seed');

INSERT OR IGNORE INTO catalog_problems (id, title, source, statement, year, session, number, area, topics_json, concepts_json, techniques_json, prerequisites_json, difficulty_overall, difficulty_insight, difficulty_technical, difficulty_prerequisite, difficulty_proof, difficulty_confidence, key_observation, solution_architecture, common_false_starts_json, classification_status) VALUES
  ('putnam_1962_a5', '1962 Putnam A5', '1962 William Lowell Putnam Mathematical Competition A5', 'Evaluate in closed form sum_{k=1}^n binom(n,k) k^2.', 1962, 'A', 5, 'Combinatorics', '["Combinatorics","Algebra"]', '["Binomial coefficients","Binomial moments","Generating functions"]', '["Differentiate a generating function","Rewrite k^2 as k(k-1)+k","Double counting"]', '["Binomial theorem","Basic differentiation"]', 3.0, 3.5, 2.0, 2.0, 2.5, 0.75, 'The factors k and k(k-1) arise from the first and second derivatives of (1+x)^n.', 'Split k^2, evaluate the two standard differentiated binomial sums at x=1, and simplify.', '["Expanding individual binomial coefficients","Attempting induction before looking for a generating function"]', 'reviewed_seed');
