PRAGMA foreign_keys = ON;

INSERT OR IGNORE INTO catalog_problems (id, title, source, statement, year, session, number, area, topics_json, concepts_json, techniques_json, prerequisites_json, difficulty_overall, difficulty_insight, difficulty_technical, difficulty_prerequisite, difficulty_proof, difficulty_confidence, key_observation, solution_architecture, common_false_starts_json, classification_status) VALUES
  ('putnam_1962_a6', '1962 Putnam A6', '1962 William Lowell Putnam Mathematical Competition A6', 'Let S be a set of rational numbers closed under addition and multiplication, and suppose that for every rational r exactly one of r in S, -r in S, or r=0 holds. Prove that S is the set of all positive rational numbers.', 1962, 'A', 6, 'Algebra', '["Algebra","Ordered fields"]', '["Positive cone","Order axioms","Rational numbers"]', '["Build an order from an algebraic cone","Derive membership of 1","Contradiction using closure"]', '["Rational arithmetic","Basic field properties","Proof by contradiction"]', 6.5, 6.5, 5.0, 3.5, 6.0, 0.6, 'The hypotheses make S a candidate positive cone; once 1 is shown to lie in S, all positive rationals follow by closure and trichotomy.', 'Rule out -1, obtain positive integers and reciprocals, and then classify every rational by sign.', '["Assuming closure under division","Using the usual order on Q before proving it agrees with S"]', 'reviewed_seed');

INSERT OR IGNORE INTO catalog_problems (id, title, source, statement, year, session, number, area, topics_json, concepts_json, techniques_json, prerequisites_json, difficulty_overall, difficulty_insight, difficulty_technical, difficulty_prerequisite, difficulty_proof, difficulty_confidence, key_observation, solution_architecture, common_false_starts_json, classification_status) VALUES
  ('putnam_1962_b1', '1962 Putnam B1', '1962 William Lowell Putnam Mathematical Competition B1', 'Let x^(n)=x(x-1)...(x-n+1) and x^(0)=1. Prove (x+y)^(n)=sum_{k=0}^n binom(n,k)x^(k)y^(n-k).', 1962, 'B', 1, 'Combinatorics', '["Combinatorics","Algebra"]', '["Falling factorials","Vandermonde identity","Polynomial identities"]', '["Combinatorial proof","Polynomial identity principle","Count by partitioning choices"]', '["Binomial coefficients","Counting injections","Polynomials"]', 3.5, 4.0, 2.5, 2.5, 3.0, 0.7, 'For nonnegative integer x,y, both sides count ordered selections of n distinct objects from two disjoint groups.', 'Prove the identity combinatorially on infinitely many integer pairs, then invoke polynomial identity, or manipulate generating functions directly.', '["Expanding every falling factorial into powers","Treating falling factorial notation as ordinary exponentiation"]', 'reviewed_seed');

INSERT OR IGNORE INTO catalog_problems (id, title, source, statement, year, session, number, area, topics_json, concepts_json, techniques_json, prerequisites_json, difficulty_overall, difficulty_insight, difficulty_technical, difficulty_prerequisite, difficulty_proof, difficulty_confidence, key_observation, solution_architecture, common_false_starts_json, classification_status) VALUES
  ('putnam_1962_b2', '1962 Putnam B2', '1962 William Lowell Putnam Mathematical Competition B2', 'Let S be the set of all subsets of the natural numbers. Prove there exists f:R->S such that f(a) is a proper subset of f(b) whenever a<b.', 1962, 'B', 2, 'Mixed', '["Set theory","Order theory"]', '["Order embedding","Dedekind cuts","Countable dense sets"]', '["Encode reals by rational cuts","Explicit construction","Verify strict inclusion"]', '["Countability of Q","Density of rational numbers","Set inclusion"]', 5.0, 5.5, 3.0, 3.5, 4.0, 0.7, 'Enumerate the rationals and represent each real number by the indices of rationals lying below it.', 'Choose a bijection N->Q, define f(a) from the lower rational cut at a, and use density of Q to prove proper inclusion.', '["Using binary expansions, which are not naturally nested","Trying to assign a unique singleton to each real"]', 'reviewed_seed');

INSERT OR IGNORE INTO catalog_problems (id, title, source, statement, year, session, number, area, topics_json, concepts_json, techniques_json, prerequisites_json, difficulty_overall, difficulty_insight, difficulty_technical, difficulty_prerequisite, difficulty_proof, difficulty_confidence, key_observation, solution_architecture, common_false_starts_json, classification_status) VALUES
  ('putnam_1962_b3', '1962 Putnam B3', '1962 William Lowell Putnam Mathematical Competition B3', 'Let S be a convex region in the Euclidean plane containing the origin, and suppose every ray from the origin has at least one point outside S. Assuming either that the origin is interior to S or that S is closed, prove S is bounded.', 1962, 'B', 3, 'Mixed', '["Real analysis","Convex geometry"]', '["Convexity","Compactness of the unit circle","Radial functions"]', '["Compactness argument","Normalize an unbounded sequence","Pass to a convergent subsequence"]', '["Sequences in R^2","Compactness","Convex sets"]', 6.0, 6.5, 4.0, 5.0, 6.0, 0.6, 'An unbounded sequence in S has directions converging to a limiting ray; convexity plus the closure/interior hypothesis forces the whole limiting ray into S.', 'Assume unboundedness, normalize points to directions, take a subsequential limit, and show arbitrarily distant points on the limiting ray belong to S.', '["Assuming the radial boundary function is automatically continuous","Using closedness when only the interior alternative is given"]', 'reviewed_seed');

INSERT OR IGNORE INTO catalog_problems (id, title, source, statement, year, session, number, area, topics_json, concepts_json, techniques_json, prerequisites_json, difficulty_overall, difficulty_insight, difficulty_technical, difficulty_prerequisite, difficulty_proof, difficulty_confidence, key_observation, solution_architecture, common_false_starts_json, classification_status) VALUES
  ('putnam_1962_b5', '1962 Putnam B5', '1962 William Lowell Putnam Mathematical Competition B5', 'For every integer n>1 prove (3n+1)/(2n+2) < sum_{k=1}^n (k/n)^n < 2.', 1962, 'B', 5, 'Mixed', '["Inequalities","Real analysis"]', '["Power sums","Geometric comparison","Integral bounds"]', '["Compare consecutive terms","Bound by a geometric series","Isolate dominant terms"]', '["Geometric series","Elementary inequalities"]', 7.0, 7.0, 5.0, 3.0, 6.0, 0.5, 'Near k=n the terms can be indexed by distance from n and bounded using (1-j/n)^n <= e^{-j} or an elementary geometric estimate.', 'Reindex from the top, derive an upper geometric bound, and obtain the lower bound from a small set of largest terms plus a tailored estimate.', '["Replacing the sum by a crude integral that misses the stated constants","Bounding every term by 1"]', 'reviewed_seed');
