PRAGMA foreign_keys = ON;

INSERT OR IGNORE INTO catalog_problems (id, title, source, statement, year, session, number, area, topics_json, concepts_json, techniques_json, prerequisites_json, difficulty_overall, difficulty_insight, difficulty_technical, difficulty_prerequisite, difficulty_proof, difficulty_confidence, key_observation, solution_architecture, common_false_starts_json, classification_status) VALUES
  ('putnam_1962_b6', '1962 Putnam B6', '1962 William Lowell Putnam Mathematical Competition B6', 'Let f(x)=sum_{k=0}^n a_k sin(kx)+b_k cos(kx). If |f(x)|<=1 on [0,2pi] and |f(x_i)|=1 at 2n distinct points, prove f(x)=cos(nx+a) for some a.', 1962, 'B', 6, 'Mixed', '["Real analysis","Trigonometric polynomials"]', '["Zero counting","Extremal trigonometric polynomials","Alternation"]', '["Convert to an algebraic polynomial","Count zeros with multiplicity","Exploit equality cases"]', '["Trigonometric polynomials","Complex numbers","Polynomial root bounds"]', 8.5, 8.5, 7.0, 6.0, 8.0, 0.55, 'At each point where |f| reaches 1, the derivative vanishes; the resulting zero count nearly saturates the degree bound.', 'Use extremal points to force many zeros of f'', classify the degree-n trigonometric polynomial with that zero pattern, and impose the amplitude bound.', '["Counting only zeros of f rather than critical points","Assuming the x_i alternate between +1 and -1 without proof"]', 'reviewed_seed');

INSERT OR IGNORE INTO catalog_problems (id, title, source, statement, year, session, number, area, topics_json, concepts_json, techniques_json, prerequisites_json, difficulty_overall, difficulty_insight, difficulty_technical, difficulty_prerequisite, difficulty_proof, difficulty_confidence, key_observation, solution_architecture, common_false_starts_json, classification_status) VALUES
  ('putnam_1963_a2', '1963 Putnam A2', '1963 William Lowell Putnam Mathematical Competition A2', 'Let f(n) be a strictly increasing sequence of positive integers with f(2)=2 and f(mn)=f(m)f(n) whenever m,n are relatively prime. Prove f(n)=n for every positive integer n.', 1963, 'A', 2, 'Algebra', '["Number theory","Algebra"]', '["Multiplicative functions","Prime powers","Monotonicity"]', '["Compare carefully chosen coprime numbers","Squeeze by powers","Reduce to prime powers"]', '["Prime factorization","Coprimality","Inequalities"]', 5.0, 6.0, 4.0, 3.0, 5.0, 0.6, 'Multiplicativity handles coprime factors, while monotonicity lets one compare prime powers to nearby powers of 2.', 'Determine f on primes or prime powers using asymptotic comparisons, then extend by unique factorization.', '["Assuming complete multiplicativity","Trying to apply the relation to p and p repeatedly"]', 'reviewed_seed');

INSERT OR IGNORE INTO catalog_problems (id, title, source, statement, year, session, number, area, topics_json, concepts_json, techniques_json, prerequisites_json, difficulty_overall, difficulty_insight, difficulty_technical, difficulty_prerequisite, difficulty_proof, difficulty_confidence, key_observation, solution_architecture, common_false_starts_json, classification_status) VALUES
  ('putnam_1963_a3', '1963 Putnam A3', '1963 William Lowell Putnam Mathematical Competition A3', 'Find an integral formula for the solution of delta(delta-1)...(delta-n+1)y=f(x), with y(1)=...=y^(n-1)(1)=0, where delta=x d/dx.', 1963, 'A', 3, 'Mixed', '["Differential equations","Real analysis"]', '["Euler differential operator","Green kernel","Repeated integration"]', '["Factor an operator","Change variables or conjugate operators","Verify a proposed integral kernel"]', '["Ordinary differential equations","Differentiation under the integral sign","Repeated derivatives"]', 6.0, 6.5, 6.0, 5.5, 5.5, 0.55, 'The product of shifted Euler operators simplifies after dividing by a power of x or changing to logarithmic coordinates.', 'Transform the operator, integrate n times using the zero initial data, derive the kernel, and verify by differentiation.', '["Expanding the entire differential operator","Forgetting the t^{-n} factor in the kernel"]', 'reviewed_seed');

INSERT OR IGNORE INTO catalog_problems (id, title, source, statement, year, session, number, area, topics_json, concepts_json, techniques_json, prerequisites_json, difficulty_overall, difficulty_insight, difficulty_technical, difficulty_prerequisite, difficulty_proof, difficulty_confidence, key_observation, solution_architecture, common_false_starts_json, classification_status) VALUES
  ('putnam_1963_a4', '1963 Putnam A4', '1963 William Lowell Putnam Mathematical Competition A4', 'For every sequence of positive reals a_n, prove limsup n((1+a_{n+1})/a_n-1)>=1, and show 1 is best possible.', 1963, 'A', 4, 'Mixed', '["Real analysis","Sequences"]', '["Limit superior","Recursive inequalities","Asymptotic comparison"]', '["Assume a uniform upper bound","Iterate a recurrence","Construct an extremal example"]', '["Limsup","Sequences and series","Logarithmic estimates"]', 7.0, 7.5, 5.5, 5.0, 6.5, 0.55, 'If the expression stayed below 1-epsilon, the sequence would be forced into an impossible growth/decay regime after iteration.', 'Negate the limsup claim, derive a recursive inequality for a_{n+1}, iterate or telescope it, reach a contradiction, then exhibit a near-sharp sequence.', '["Treating limsup as an ordinary limit","Guessing a_n=1/n without checking the exact expression"]', 'reviewed_seed');

INSERT OR IGNORE INTO catalog_problems (id, title, source, statement, year, session, number, area, topics_json, concepts_json, techniques_json, prerequisites_json, difficulty_overall, difficulty_insight, difficulty_technical, difficulty_prerequisite, difficulty_proof, difficulty_confidence, key_observation, solution_architecture, common_false_starts_json, classification_status) VALUES
  ('putnam_1963_a6', '1963 Putnam A6', '1963 William Lowell Putnam Mathematical Competition A6', 'Let U,V be distinct points on an ellipse, M their chord midpoint, and AB,CD two other chords through M. If UV meets AC at P and BD at Q, prove M is the midpoint of PQ.', 1963, 'A', 6, 'Geometry', '["Geometry","Affine geometry","Conics"]', '["Ellipse","Affine transformations","Midpoints"]', '["Affine normalization","Coordinate geometry","Use symmetry of a conic"]', '["Analytic geometry","Affine maps","Linear equations"]', 7.5, 7.5, 6.5, 4.5, 6.5, 0.5, 'An affine map sends the ellipse to a circle while preserving lines, intersections, and midpoints.', 'Normalize the conic and midpoint with affine coordinates, parametrize the chords, compute P and Q, and show their position vectors sum to 2M.', '["Angle chasing, which is not affine-invariant","Choosing coordinates centered at the ellipse rather than at the relevant midpoint without simplification"]', 'reviewed_seed');
