PRAGMA foreign_keys = ON;

INSERT OR IGNORE INTO catalog_problems (id, title, source, statement, year, session, number, area, topics_json, concepts_json, techniques_json, prerequisites_json, difficulty_overall, difficulty_insight, difficulty_technical, difficulty_prerequisite, difficulty_proof, difficulty_confidence, key_observation, solution_architecture, common_false_starts_json, classification_status) VALUES
  ('putnam_1963_b1', '1963 Putnam B1', '1963 William Lowell Putnam Mathematical Competition B1', 'For what integer a does x^2-x+a divide x^13+x+90?', 1963, 'B', 1, 'Algebra', '["Algebra","Polynomials","Number theory"]', '["Polynomial divisibility","Remainders modulo a quadratic","Linear recurrences"]', '["Reduce powers using a quadratic relation","Track a recurrence","Use integrality/divisibility constraints"]', '["Polynomial division","Recurrences","Integer arithmetic"]', 3.5, 4.0, 4.0, 2.5, 3.5, 0.7, 'Modulo x^2-x+a, every high power reduces to a linear polynomial whose coefficients satisfy a recurrence in a.', 'Compute or control the remainder of x^13+x+90 modulo the quadratic, set both coefficients to zero, and solve the resulting integer conditions.', '["Factoring x^13+x+90 directly","Testing many integer values without deriving constraints"]', 'reviewed_seed');

INSERT OR IGNORE INTO catalog_problems (id, title, source, statement, year, session, number, area, topics_json, concepts_json, techniques_json, prerequisites_json, difficulty_overall, difficulty_insight, difficulty_technical, difficulty_prerequisite, difficulty_proof, difficulty_confidence, key_observation, solution_architecture, common_false_starts_json, classification_status) VALUES
  ('putnam_1963_b2', '1963 Putnam B2', '1963 William Lowell Putnam Mathematical Competition B2', 'Let S={2^m 3^n : m,n are integers}. Is S dense in the positive real numbers?', 1963, 'B', 2, 'Mixed', '["Number theory","Real analysis"]', '["Density","Irrational logarithm ratios","Additive subgroups"]', '["Take logarithms","Use irrational rotations or Diophantine approximation","Transfer density through a continuous map"]', '["Logarithms","Density modulo 1","Irrational numbers"]', 5.0, 5.5, 3.5, 4.0, 4.5, 0.65, 'Taking logarithms turns products 2^m3^n into the additive set m log 2+n log 3; log 2/log 3 is irrational.', 'Prove irrationality of the log ratio, establish density of the generated additive subgroup, and exponentiate.', '["Assuming every two-generator subgroup of R is dense","Using only nonnegative exponents"]', 'reviewed_seed');

INSERT OR IGNORE INTO catalog_problems (id, title, source, statement, year, session, number, area, topics_json, concepts_json, techniques_json, prerequisites_json, difficulty_overall, difficulty_insight, difficulty_technical, difficulty_prerequisite, difficulty_proof, difficulty_confidence, key_observation, solution_architecture, common_false_starts_json, classification_status) VALUES
  ('putnam_1963_b3', '1963 Putnam B3', '1963 William Lowell Putnam Mathematical Competition B3', 'Find every twice-differentiable real function satisfying f(x)^2-f(y)^2=f(x+y)f(x-y) for all real x,y.', 1963, 'B', 3, 'Mixed', '["Functional equations","Differential equations","Real analysis"]', '["D''Alembert-type identity","Second-order ODE","Initial values"]', '["Substitute special values","Differentiate with respect to a parameter","Classify solutions of an ODE"]', '["Partial differentiation","Second-order linear ODEs","Functional equations"]', 6.0, 6.0, 5.5, 4.5, 5.5, 0.65, 'Setting y=0 gives f(0)=0 (outside degenerate cases), and differentiating twice in y yields f''''=cf.', 'Handle degenerate cases, derive initial constraints, differentiate the identity to obtain an ODE, solve it by the sign of the constant, and verify.', '["Dividing by f(x) before handling zeros","Guessing trigonometric solutions without proving completeness"]', 'reviewed_seed');

INSERT OR IGNORE INTO catalog_problems (id, title, source, statement, year, session, number, area, topics_json, concepts_json, techniques_json, prerequisites_json, difficulty_overall, difficulty_insight, difficulty_technical, difficulty_prerequisite, difficulty_proof, difficulty_confidence, key_observation, solution_architecture, common_false_starts_json, classification_status) VALUES
  ('putnam_1963_b5', '1963 Putnam B5', '1963 William Lowell Putnam Mathematical Competition B5', 'Let a_n be real numbers with 0<=a_k<=100a_n whenever n<=k<=2n, and suppose sum a_n converges. Prove n a_n ->0.', 1963, 'B', 5, 'Mixed', '["Real analysis","Series"]', '["Convergent nonnegative series","Block estimates","Local comparability"]', '["Sum over dyadic blocks","Contradiction from a lower block mass","Exploit a local regularity condition"]', '["Convergent series","Cauchy criterion","Sequences"]', 7.0, 7.0, 4.5, 3.5, 6.0, 0.65, 'The condition prevents a_n from being an isolated spike: if n a_n is large, an entire block near n must carry substantial mass.', 'Use the comparability inequality to lower-bound a block sum in terms of n a_n, then use convergence to force those block sums to zero.', '["Claiming n a_n->0 for every convergent positive series","Using only the single term a_n instead of a whole block"]', 'reviewed_seed');

INSERT OR IGNORE INTO catalog_problems (id, title, source, statement, year, session, number, area, topics_json, concepts_json, techniques_json, prerequisites_json, difficulty_overall, difficulty_insight, difficulty_technical, difficulty_prerequisite, difficulty_proof, difficulty_confidence, key_observation, solution_architecture, common_false_starts_json, classification_status) VALUES
  ('putnam_1963_b6', '1963 Putnam B6', '1963 William Lowell Putnam Mathematical Competition B6', 'In Euclidean space of dimension at most 3, let S(A) be the union of all closed segments joining pairs of points of A. Starting with nonempty A_0 and A_n=S(A_{n-1}), prove A_2=A_3=... .', 1963, 'B', 6, 'Mixed', '["Convex geometry","Linear algebra"]', '["Convex hull","Caratheodory''s theorem","Affine dimension"]', '["Represent convex combinations with few points","Regroup convex combinations","Dimension reduction"]', '["Convex combinations","Affine independence","Linear algebra"]', 8.0, 8.5, 6.0, 5.0, 7.5, 0.55, 'In dimension at most 3, every convex-hull point uses at most four original points, and a four-point convex combination can be grouped as a segment between two points of S(A_0).', 'Identify A_1 and A_2 as bounded-complexity convex combinations, apply the low-dimensional Caratheodory principle, regroup coefficients, and prove idempotence from A_2 onward.', '["Assuming S(A) is already convex in all dimensions","Ignoring why the dimension bound 3 is essential"]', 'reviewed_seed');
