PRAGMA foreign_keys = ON;

INSERT OR IGNORE INTO catalog_problems (id, title, source, statement, year, session, number, area, topics_json, concepts_json, techniques_json, prerequisites_json, difficulty_overall, difficulty_insight, difficulty_technical, difficulty_prerequisite, difficulty_proof, difficulty_confidence, key_observation, solution_architecture, common_false_starts_json, classification_status) VALUES
  ('putnam_1964_a1', '1964 Putnam A1', '1964 William Lowell Putnam Mathematical Competition A1', 'Six distinct points lie in the plane. Let D be the largest pairwise distance and d the smallest. Prove D/d>=sqrt(3).', 1964, 'A', 1, 'Mixed', '["Combinatorial geometry","Extremal geometry"]', '["Diameter","Minimum separation","Packing"]', '["Scale normalization","Pigeonhole principle","Geometric partition"]', '["Euclidean distance","Elementary geometry"]', 3.0, 4.0, 2.5, 2.0, 3.5, 0.65, 'After normalizing the minimum distance, too small a diameter would force six mutually separated points into a region that cannot accommodate them.', 'Normalize d=1, enclose or partition the configuration using an extremal pair, and apply a geometric packing/pigeonhole argument.', '["Assuming the six points form a convex hexagon","Using only the triangle inequality, which gives too weak a constant"]', 'reviewed_seed');

INSERT OR IGNORE INTO catalog_problems (id, title, source, statement, year, session, number, area, topics_json, concepts_json, techniques_json, prerequisites_json, difficulty_overall, difficulty_insight, difficulty_technical, difficulty_prerequisite, difficulty_proof, difficulty_confidence, key_observation, solution_architecture, common_false_starts_json, classification_status) VALUES
  ('putnam_1964_a2', '1964 Putnam A2', '1964 William Lowell Putnam Mathematical Competition A2', 'Let alpha be real. Find all continuous f:[0,1]->(0,infinity) satisfying integral f=1, integral x f=alpha, and integral x^2 f=alpha^2.', 1964, 'A', 2, 'Mixed', '["Real analysis","Inequalities","Probability"]', '["Moments","Variance","Cauchy-Schwarz equality"]', '["Reinterpret as a probability density","Use a nonnegative integral","Analyze an equality case"]', '["Integration","Cauchy-Schwarz inequality","Variance"]', 4.5, 5.0, 2.5, 3.0, 4.0, 0.75, 'The equations say E[X^2]=E[X]^2, so the variance is zero, impossible for a strictly positive continuous density on an interval.', 'Normalize f as a probability density, compute integral (x-alpha)^2 f(x), show it is zero, and contradict strict positivity away from x=alpha.', '["Trying to solve for f explicitly","Using Jensen without examining the equality case"]', 'reviewed_seed');

INSERT OR IGNORE INTO catalog_problems (id, title, source, statement, year, session, number, area, topics_json, concepts_json, techniques_json, prerequisites_json, difficulty_overall, difficulty_insight, difficulty_technical, difficulty_prerequisite, difficulty_proof, difficulty_confidence, key_observation, solution_architecture, common_false_starts_json, classification_status) VALUES
  ('putnam_1964_a3', '1964 Putnam A3', '1964 William Lowell Putnam Mathematical Competition A3', 'Distinct points x_n are dense in (0,1). When x_n splits its current containing interval into lengths a_n,b_n, prove sum a_n b_n(a_n+b_n)=1/3.', 1964, 'A', 3, 'Combinatorics', '["Real analysis","Combinatorics"]', '["Interval splitting","Telescoping sums","Potential functions"]', '["Invent a conserved potential","Telescoping over refinements","Use density to make the remainder vanish"]', '["Infinite series","Dense subsets","Algebraic identities"]', 6.0, 7.0, 4.0, 3.5, 5.5, 0.65, 'Splitting an interval of length a+b changes the sum of cubes of interval lengths by exactly 3ab(a+b).', 'Track the sum of cubes of all current interval lengths, telescope the change at each insertion, and use density to show the final mesh tends to zero.', '["Trying to calculate a_n and b_n individually","Assuming the insertion order does not matter without identifying an invariant"]', 'reviewed_seed');

INSERT OR IGNORE INTO catalog_problems (id, title, source, statement, year, session, number, area, topics_json, concepts_json, techniques_json, prerequisites_json, difficulty_overall, difficulty_insight, difficulty_technical, difficulty_prerequisite, difficulty_proof, difficulty_confidence, key_observation, solution_architecture, common_false_starts_json, classification_status) VALUES
  ('putnam_1964_a4', '1964 Putnam A4', '1964 William Lowell Putnam Mathematical Competition A4', 'A bounded integer sequence satisfies u_n=(u_{n-1}+u_{n-2}+u_{n-3}u_{n-4})/(u_{n-1}u_{n-2}+u_{n-3}+u_{n-4}). Prove it is eventually periodic.', 1964, 'A', 4, 'Mixed', '["Discrete mathematics","Recurrences"]', '["Finite-state systems","Deterministic recurrence","Eventual periodicity"]', '["Pigeonhole principle on states","Encode enough consecutive terms","Deterministic evolution"]', '["Sequences","Pigeonhole principle","Recurrences"]', 6.5, 5.5, 6.0, 2.5, 5.0, 0.7, 'Bounded integer values give only finitely many possible four-term states, and the recurrence determines the next state.', 'Form state vectors of four consecutive terms, use finiteness to find a repeated state, and invoke determinism to obtain periodicity thereafter.', '["Trying to solve the nonlinear recurrence explicitly","Applying pigeonhole to individual terms rather than full states"]', 'reviewed_seed');

INSERT OR IGNORE INTO catalog_problems (id, title, source, statement, year, session, number, area, topics_json, concepts_json, techniques_json, prerequisites_json, difficulty_overall, difficulty_insight, difficulty_technical, difficulty_prerequisite, difficulty_proof, difficulty_confidence, key_observation, solution_architecture, common_false_starts_json, classification_status) VALUES
  ('putnam_1964_b2', '1964 Putnam B2', '1964 William Lowell Putnam Mathematical Competition B2', 'Let S be finite. A maximal family P of subsets of S has the property that any two members intersect. Prove P contains exactly half of all subsets of S.', 1964, 'B', 2, 'Combinatorics', '["Combinatorics","Set theory"]', '["Intersecting families","Complements","Maximality"]', '["Pair objects with complements","Use maximality to force one choice per pair","Contradiction"]', '["Finite sets","Power sets","Set complements"]', 4.0, 4.5, 2.0, 1.5, 3.5, 0.8, 'An intersecting family cannot contain both A and its complement, while maximality forces it to contain at least one of each complementary pair.', 'Partition the power set into complementary pairs, prove exactly one member of every pair lies in P, and count the pairs.', '["Confusing maximal with maximum","Invoking the Erdos-Ko-Rado theorem, which is unnecessary"]', 'reviewed_seed');
